--changeset lukas.vierheilig:0020_insert_test_quotes
--context: dev, test-data
--comment: Insert 100 happy and inspirational quotes for development and testing.

INSERT INTO happy_quotes.quotes (text)
VALUES ('The best way to predict the future is to create it.'),
       ('The only limit to our realization of tomorrow will be our doubts of today.'),
       ('Happiness is not something readymade. It comes from your own actions.'),
       ('Believe you can and you’re halfway there.'),
       ('The mind is everything. What you think you become.'),
       ('Do what you can, with what you have, where you are.'),
       ('The journey of a thousand miles begins with a single step.'),
       ('Strive not to be a success, but rather to be of value.'),
       ('The purpose of our lives is to be happy.'),
       ('Live as if you were to die tomorrow. Learn as if you were to live forever.'),
       ('Be the change that you wish to see in the world.'),
       ('It is never too late to be what you might have been.'),
       ('The only true wisdom is in knowing you know nothing.'),
       ('You must do the things you think you cannot do.'),
       ('A person who never made a mistake never tried anything new.'),
       ('Where there is a will, there is a way.'),
       ('Change your thoughts and you change your world.'),
       ('Every moment is a fresh beginning.'),
       ('The simple act of paying attention can bring about happiness.'),
       ('Don’t count the days, make the days count.'),
       ('The future belongs to those who believe in the beauty of their dreams.'),
       ('Our greatest glory is not in never falling, but in rising every time we fall.'),
       ('If you are working on something exciting that you really care about, you don’t have to be pushed. The vision pulls you.'),
       ('The only way to do great work is to love what you do.'),
       ('It does not matter how slowly you go as long as you do not stop.'),
       ('With the new day comes new strength and new thoughts.'),
       ('What we think, we become.'),
       ('The most difficult thing is the decision to act, the rest is merely tenacity.'),
       ('I have not failed. I’ve just found 10,000 ways that won’t work.'),
       ('If you want to live a happy life, tie it to a goal, not to people or things.'),
       ('Keep your face always toward the sunshine—and shadows will fall behind you.'),
       ('The only source of knowledge is experience.'),
       ('Tension is who you think you should be. Relaxation is who you are.'),
       ('If you look at what you have in life, you’ll always have more.'),
       ('In a gentle way, you can shake the world.'),
       ('Start where you are. Use what you have. Do what you can.'),
       ('The power of imagination makes us infinite.'),
       ('The best revenge is massive success.'),
       ('Try to be a rainbow in someone’s cloud.'),
       ('Nothing is impossible, the word itself says ‘I’m possible’!'),
       ('You must expect great things of yourself before you can do them.'),
       ('The only true failure is when you stop trying.'),
       ('Happiness is when what you think, what you say, and what you do are in harmony.'),
       ('Success is not final, failure is not fatal: it is the courage to continue that counts.'),
       ('The greatest glory in living lies not in never falling, but in rising every time we fall.'),
       ('Life is what happens when you’re busy making other plans.'),
       ('May your choices reflect your hopes, not your fears.'),
       ('The best time to plant a tree was 20 years ago. The second best time is now.'),
       ('If you want to lift yourself up, lift up someone else.'),
       ('When you change your thoughts, remember to change your world.'),
       ('Optimism is the faith that leads to achievement.'),
       ('Don’t wait for the right opportunity: create it.'),
       ('We can’t solve problems by using the same kind of thinking we used when we created them.'),
       ('The time is always right to do what is right.'),
       ('The difference between stumbling blocks and stepping stones is how you use them.'),
       ('A truly happy person is one who can enjoy the scenery on a detour.'),
       ('Doubt kills more dreams than failure ever will.'),
       ('The grass is greener where you water it.'),
       ('To dare is to lose one’s footing momentarily. Not to dare is to lose oneself.'),
       ('Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it.'),
       ('You are never too old to set another goal or to dream a new dream.'),
       ('What lies behind us and what lies before us are tiny matters compared to what lies within us.'),
       ('It’s not what happens to you, but how you react to it that matters.'),
       ('The best preparation for tomorrow is doing your best today.'),
       ('Happiness is the secret to all beauty.'),
       ('Let your unique awesomeness and positive energy inspire confidence in others.'),
       ('The greatest weapon against stress is our ability to choose one thought over another.'),
       ('Be happy for this moment. This moment is your life.'),
       ('Every strike brings me closer to the next home run.'),
       ('I choose to make the rest of my life the best of my life.'),
       ('Happiness is a state of activity.'),
       ('The purpose of life is not to be happy. It is to be useful.'),
       ('When you cannot find the sunshine, be the sunshine.'),
       ('You miss 100% of the shots you don’t take.'),
       ('The only way around is through.'),
       ('A smile is the universal welcome.'),
       ('The day always looks brighter from behind a smile.'),
       ('Do something today that your future self will thank you for.'),
       ('Life is 10% what happens to you and 90% how you react to it.'),
       ('Wherever you go, go with all your heart.'),
       ('The only true failure is in giving up.'),
       ('Success is the sum of small efforts, repeated day in and day out.'),
       ('It’s not whether you get knocked down, it’s whether you get up.'),
       ('No one can make you feel inferior without your consent.'),
       ('The sun always shines above the clouds.'),
       ('I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.'),
       ('Keep your eyes on the stars, and your feet on the ground.'),
       ('The best curve on a woman’s body is her smile.'),
       ('Don’t watch the clock; do what it does. Keep going.'),
       ('Go confidently in the direction of your dreams!'),
       ('The biggest adventure you can take is to live the life of your dreams.'),
       ('Happiness is not a destination; it is a method of life.'),
       ('The measure of who we are is what we do with what we have.'),
       ('Be brave enough to live life creatively.'),
       ('Action is the foundational key to all success.'),
       ('The time to be happy is now.'),
       ('Simplicity is the ultimate sophistication.'),
       ('We are shaped and fashioned by what we love.'),
       ('The truest greatness lies in being kind.'),
       ('Keep your face to the sun and you will never see the shadows.'),
       ('The glow of satisfaction is the greatest beauty.'),
       ('Do small things with great love.'),
       ('Today is a new day. You should start fresh, be happy and inspire others.'),
       ('You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.'),
       ('Every flower is a soul blossoming in nature.'),
       ('The joy we feel has little to do with the circumstances of our lives and everything to do with the focus of our lives.')
;