
### All quotes
GET {{host}}/api/quotes
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, `Response status is not 200 -> ${response.status}`);
    });
%}

### A random quote
GET {{host}}/api/quotes/random
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, `Response status is not 200 -> ${response.status}`);
    });
%}


### Create a new quote
POST {{host}}/api/quotes
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "text": "A person who never made a mistake never tried anything new."
}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 201, `Response status is not 201 -> ${response.status}`);
    });
    const locationHeader = response.headers.valueOf("Location");

    client.test("Location header is present", function () {
        client.assert(!!locationHeader, "Location header is missing.");
    });

    if (locationHeader) {
        client.global.set("dynamicHostCreatedQuote", locationHeader);
    }
%}


### Get the newly created quote
GET {{dynamicHostCreatedQuote}}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, `Response status is not 200 -> ${response.status}`);
    });
%}


### Get qr code of newly created quote
GET {{dynamicHostCreatedQuote}}/qr
Content-Type: image/png

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, `Response status is not 200 -> ${response.status}`);
    });
%}

### Delete newly created quote
DELETE {{dynamicHostCreatedQuote}}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 204, `Response status is not 204 -> ${response.status}`);
    });
%}


